[pytest]
testpaths = app/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short

[coverage:run]
source = app
omit =
    app/tests/*
    app/db/session.py

[coverage:report]
show_missing = true
skip_covered = false
